### ISSUE TITLE
Question on Texture 

### ISSUE THREAD

**Issue by TharHtetAungg** [taconite/IntrinsicAvatar#1]
Does your repo generate a traditional texture map? And also does it generate a 3D mesh model? 

Thanks.

**Comment by taconite** [comment]
In the paper, all the visualizations and evaluations are based on volumetric rendering/scattering. But it is possible to extract mesh and corresponding texture/material/normal maps from learned neural fields - actually we are working on a demo for this, so please stay tuned ;)

**Comment by TharHtetAungg** [comment]
I am looking forward your update. Thanks.
