### ISSUE TITLE
Code release ? 

### ISSUE THREAD

**Issue by TharHtetAungg** [taconite/IntrinsicAvatar#2]
Hi, when will you release your code?

**Comment by BukenyaLukman** [comment]
Sure. I am also waiting for it. Guys release beautiful papers and refuse to release code.

**Comment by taconite** [comment]
Hi, thank you for your interest in our paper!

We plan to release our code in March.

**Comment by Jiatttliu** [comment]
Hello,Is the code ready for release? @taconite

**Comment by TharHtetAungg** [comment]
Any update ?
