### ISSUE TITLE
ImportError: cannot import name 'rgb_to_srgb' from 'lib.torch_pbr' (unknown location)

### ISSUE THREAD

**Issue by TharHtetAungg** [taconite/IntrinsicAvatar#3]
I got this error when I run training. And also could you please tell me file location for dataset.

**Comment by SherlockSunset** [comment]
Hi, may I know how you solved this issue?

**Comment by SherlockSunset** [comment]
ok, already solved. I just manually downloaded the **torch_pbr** project and placed it unfer the **lib** folder.
