### ISSUE TITLE
Error for SSIM metrics calculation

### ISSUE THREAD

**Issue by SherlockSunset** [taconite/IntrinsicAvatar#8]
Hi Thanks for the great project! I tried to train **male-3-casual** using the codes, but it showed that SSIM calculation error when the Epoch is 17 (just as the image attached). Hope can help me out, thanks in advance.

![企业微信截图_17282939175455](https://github.com/user-attachments/assets/5530c501-ddf4-4a19-93a0-9404bae39f00)

**Comment by taconite** [comment]
Hi,

Seems like you are using the latest scikit-image which has a different interface for SSIM than what has been used in this repo. Please follow the installation instructions of this repo and install `scikit-image==0.18.1` instead, this should resolve the issue.

**Comment by SherlockSunset** [comment]
ok, fixed already. Thanks.
